limit_req_zone $binary_remote_addr zone=api_por_ip:10m rate=20r/s;

upstream vic_api {
    least_conn;
    keepalive 16;
    server 10.20.0.20:8001 max_fails=3 fail_timeout=10s;
    server 10.20.0.20:8002 max_fails=3 fail_timeout=10s;
}

server {
    listen 80;
    server_name _;
    return 301 https://$host:8443$request_uri;
}

server {
    listen 443 ssl;
    server_name _;

    ssl_certificate /etc/nginx/certs/vic.crt;
    ssl_certificate_key /etc/nginx/certs/vic.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_prefer_server_ciphers off;

    add_header Strict-Transport-Security "max-age=31536000" always;
    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options DENY always;
    add_header Referrer-Policy no-referrer always;

    root /usr/share/nginx/html;
    index index.html;
    client_max_body_size 9m;

    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types application/javascript application/json image/svg+xml text/css text/plain;

    location = /salud-publica {
        access_log off;
        default_type application/json;
        return 200 '{"estado":"ok","servidor":"publico"}';
    }

    location = /api/metricas {
        return 404;
    }

    location /api/ {
        limit_req zone=api_por_ip burst=40 nodelay;
        proxy_pass http://vic_api/;
        proxy_http_version 1.1;
        proxy_connect_timeout 5s;
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
        proxy_set_header Host $host;
        proxy_set_header Connection "";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto https;
        add_header X-VIC-Balanceador nginx always;
    }

    location /evidencias/ {
        proxy_pass http://vic_api/evidencias/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        expires 1h;
        add_header Cache-Control "public";
    }

    location /grafana/ {
        proxy_pass http://10.20.0.20:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect ~^https?://[^/]+(/grafana/.*)$ $scheme://$http_host$1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /_expo/static/ {
        try_files $uri =404;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location = /index.html {
        add_header Cache-Control "no-store";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
